import { LogicMonitorDevice } from '../interfaces/discovery/index';

const logicmonitorMockData: LogicMonitorDevice[] = [
    {
        logCollectorGroupId: 0,
        disableAlerting: true,
        netflowCollectorGroupId: 0,
        rolePrivileges: ["string"],
        systemProperties: [{ name: "addr", value: "127.0.0.1" }],
        isPreferredLogCollectorConfigured: true,
        hostStatus: "string",
        autoBalancedCollectorGroupId: 0,
        inheritedProperties: [{ name: "addr", value: "127.0.0.1" }],
        id: 1,
        syntheticsCollectorIds: "1,4",
        upTimeInSeconds: 0,
        deviceType: 0,
        currentCollectorId: 1,
        netflowCollectorId: 1,
        autoPropsAssignedOn: 0,
        updatedOn: 0,
        preferredCollectorGroupId: 0,
        customProperties: [{ name: "addr", value: "127.0.0.1" }],
        collectorDescription: "string",
        preferredCollectorId: 2,
        lastRawdataTime: 0,
        name: "Device 1",
        deletedTimeInMs: 0,
        netflowCollectorGroupName: "string",
        azureState: 0,
        relatedDeviceId: -1,
        logCollectorGroupName: "string",
        displayName: "Device 1 Display Name",
        logCollectorDescription: "string",
        link: "www.device1.com",
        awsState: 0,
        description: "This is Device 1",
        createdOn: 0,
        gcpState: 0,
        autoPropsUpdatedOn: 0,
        scanConfigId: 0,
        enableNetflow: true,
        lastDataTime: 0,
        hostGroupIds: "16,4,3",
        resourceIds: [{ name: "addr", value: "127.0.0.1" }],
        op: "string",
        currentLogCollectorId: 1,
        logCollectorId: 1,
        netflowCollectorDescription: "string",
        userPermission: "string",
        preferredCollectorGroupName: "string",
        autoProperties: [{ name: "addr", value: "127.0.0.1" }],
        toDeleteTimeInMs: 0,
    },
    {
        logCollectorGroupId: 0,
        disableAlerting: true,
        netflowCollectorGroupId: 0,
        rolePrivileges: ["string"],
        systemProperties: [{ name: "addr", value: "127.0.0.2" }],
        isPreferredLogCollectorConfigured: true,
        hostStatus: "string",
        autoBalancedCollectorGroupId: 0,
        inheritedProperties: [{ name: "addr", value: "127.0.0.2" }],
        id: 2,
        syntheticsCollectorIds: "2,5",
        upTimeInSeconds: 0,
        deviceType: 1,
        currentCollectorId: 2,
        netflowCollectorId: 2,
        autoPropsAssignedOn: 0,
        updatedOn: 0,
        preferredCollectorGroupId: 0,
        customProperties: [{ name: "addr", value: "127.0.0.2" }],
        collectorDescription: "string",
        preferredCollectorId: 3,
        lastRawdataTime: 0,
        name: "Device 2",
        deletedTimeInMs: 0,
        netflowCollectorGroupName: "string",
        azureState: 0,
        relatedDeviceId: -1,
        logCollectorGroupName: "string",
        displayName: "Device 2 Display Name",
        logCollectorDescription: "string",
        link: "www.device2.com",
        awsState: 0,
        description: "This is Device 2",
        createdOn: 0,
        gcpState: 0,
        autoPropsUpdatedOn: 0,
        scanConfigId: 0,
        enableNetflow: true,
        lastDataTime: 0,
        hostGroupIds: "16,4,3",
        resourceIds: [{ name: "addr", value: "127.0.0.2" }],
        op: "string",
        currentLogCollectorId: 2,
        logCollectorId: 2,
        netflowCollectorDescription: "string",
        userPermission: "string",
        preferredCollectorGroupName: "string",
        autoProperties: [{ name: "addr", value: "127.0.0.2" }],
        toDeleteTimeInMs: 0,
    },
    {
        logCollectorGroupId: 0,
        disableAlerting: true,
        netflowCollectorGroupId: 0,
        rolePrivileges: ["string"],
        systemProperties: [{ name: "addr", value: "127.0.0.3" }],
        isPreferredLogCollectorConfigured: true,
        hostStatus: "string",
        autoBalancedCollectorGroupId: 0,
        inheritedProperties: [{ name: "addr", value: "127.0.0.3" }],
        id: 3,
        syntheticsCollectorIds: "3,6",
        upTimeInSeconds: 0,
        deviceType: 2,
        currentCollectorId: 3,
        netflowCollectorId: 3,
        autoPropsAssignedOn: 0,
        updatedOn: 0,
        preferredCollectorGroupId: 0,
        customProperties: [{ name: "addr", value: "127.0.0.3" }],
        collectorDescription: "string",
        preferredCollectorId: 4,
        lastRawdataTime: 0,
        name: "Device 3",
        deletedTimeInMs: 0,
        netflowCollectorGroupName: "string",
        azureState: 0,
        relatedDeviceId: -1,
        logCollectorGroupName: "string",
        displayName: "Device 3 Display Name",
        logCollectorDescription: "string",
        link: "www.device3.com",
        awsState: 0,
        description: "This is Device 3",
        createdOn: 0,
        gcpState: 0,
        autoPropsUpdatedOn: 0,
        scanConfigId: 0,
        enableNetflow: true,
        lastDataTime: 0,
        hostGroupIds: "16,4,3",
        resourceIds: [{ name: "addr", value: "127.0.0.3" }],
        op: "string",
        currentLogCollectorId: 3,
        logCollectorId: 3,
        netflowCollectorDescription: "string",
        userPermission: "string",
        preferredCollectorGroupName: "string",
        autoProperties: [{ name: "addr", value: "127.0.0.3" }],
        toDeleteTimeInMs: 0,
    }
];

export {logicmonitorMockData};